import React, { useState, useEffect } from 'react';
import api from '../../utils/api';
import { Search, Download, Share2, Printer, Eye } from 'lucide-react';
import toast from 'react-hot-toast';

const ReceiptHistory = ({ defaultCategory = 'All', hideTitle = false }) => {
  const [receipts, setReceipts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [filters, setFilters] = useState({
    category: defaultCategory,
    branchId: 'All',
    search: ''
  });

  const categories = ['All', 'Notice', 'Donation', 'Branch Donation', 'Annadan', 'Prasad', 'Payment', 'Expense'];

  const fetchReceipts = async () => {
    try {
      setLoading(true);
      const queryParams = new URLSearchParams(filters).toString();
      const res = await api.get(`/receipts?${queryParams}`);
      if (res.data.success) {
        setReceipts(res.data.data);
      }
    } catch (error) {
      toast.error('Failed to load receipts');
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReceipts();
  }, [filters.category, filters.branchId]);

  const handleSearch = (e) => {
    e.preventDefault();
    fetchReceipts();
  };

  return (
    <div className="p-6 bg-gray-50 min-h-screen">
      <div className="max-w-7xl mx-auto">
        {!hideTitle && <h1 className="text-3xl font-bold text-gray-900 mb-6 border-b border-gray-100 pb-4">Document & Receipt History</h1>}

        {/* Filters */}
        <div className="bg-white p-4 md:p-5 rounded-xl shadow-sm mb-6 flex flex-col sm:flex-row flex-wrap gap-4 items-stretch sm:items-end border border-gray-100">
          <div className="flex-1 min-w-[200px]">
            <label className="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Search Document No.</label>
            <form onSubmit={handleSearch} className="relative">
              <input
                type="text"
                placeholder="Search REC-..."
                className="w-full pl-10 pr-4 py-2 border rounded-lg focus:ring-2 focus:ring-red-500 outline-none"
                value={filters.search}
                onChange={(e) => setFilters({ ...filters, search: e.target.value })}
              />
              <Search className="absolute left-3 top-2.5 text-gray-400 w-5 h-5" />
            </form>
          </div>
          
          <div className="min-w-[150px]">
            <label className="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Category</label>
            <select
              className="w-full p-2 border rounded-lg bg-gray-50"
              value={filters.category}
              onChange={(e) => setFilters({ ...filters, category: e.target.value })}
            >
              {categories.map(cat => <option key={cat} value={cat}>{cat}</option>)}
            </select>
          </div>
          
          <button 
            onClick={fetchReceipts}
            className="px-6 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 transition"
          >
            Apply Filters
          </button>
        </div>

        {/* Table */}
        <div className="md:bg-white md:rounded-xl md:shadow-sm overflow-hidden relative z-10">
          <div className="w-full overflow-hidden">
            <table className="w-full text-left text-sm block md:table">
              <thead className="bg-gray-50 hidden md:table-header-group border-b border-gray-100">
                <tr>
                  <th className="p-4 md:p-6 text-xs font-bold text-gray-500 uppercase tracking-wider">Document No</th>
                  <th className="p-4 md:p-6 text-xs font-bold text-gray-500 uppercase tracking-wider">Date</th>
                  <th className="p-4 md:p-6 text-xs font-bold text-gray-500 uppercase tracking-wider">Category</th>
                  <th className="p-4 md:p-6 text-xs font-bold text-gray-500 uppercase tracking-wider">Recipient</th>
                  <th className="p-4 md:p-6 text-xs font-bold text-gray-500 uppercase tracking-wider">Branch</th>
                  <th className="p-4 md:p-6 text-xs font-bold text-gray-500 uppercase tracking-wider">Generated By</th>
                  <th className="p-4 md:p-6 text-xs font-bold text-gray-500 uppercase tracking-wider text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="block md:table-row-group w-full divide-y divide-gray-100">
                {loading ? (
                  <tr><td colSpan="6" className="text-center p-8 text-gray-500">Loading documents...</td></tr>
                ) : receipts.length === 0 ? (
                  <tr><td colSpan="6" className="text-center p-8 text-gray-500">No documents found matching filters</td></tr>
                ) : (
                  receipts.map(receipt => (
                    <tr key={receipt._id} className="flex flex-col md:table-row w-full bg-white md:bg-transparent border border-gray-100 md:border-b md:border-x-0 md:border-t-0 md:border-gray-200 rounded-xl md:rounded-none mb-4 md:mb-0 shadow-sm md:shadow-none hover:bg-gray-50 overflow-hidden transition">
                      {/* Mobile Card Top & Desktop ID */}
                      <td className="p-3 md:p-6 flex flex-col md:table-cell w-full border-b border-gray-50 md:border-none">
                        <div className="flex md:hidden justify-between items-start mb-3">
                          <span className="text-xs font-bold text-gray-500 uppercase tracking-wider">No: {receipt.receiptNumber}</span>
                          <span className="px-2.5 py-1 bg-blue-50 text-blue-700 border border-blue-200 rounded-full text-[10px] font-bold">
                            {receipt.category}
                          </span>
                        </div>
                        <div className="md:hidden mb-2">
                          <span className="text-xs font-bold text-gray-500 uppercase tracking-wider block mb-0.5">Recipient</span>
                          <span className="font-bold text-gray-900 text-sm break-words whitespace-normal">{receipt.dynamicData?.donorName || receipt.dynamicData?.name || receipt.dynamicData?.subject || 'N/A'}</span>
                        </div>
                        <div className="md:hidden mb-1 break-words whitespace-normal">
                          <span className="text-xs font-bold text-gray-500 uppercase tracking-wider mr-2">Branch:</span>
                          <span className="text-sm font-semibold text-gray-700">{receipt.branchId?.name || 'Main Trust'}</span>
                        </div>
                        {/* Desktop view Content */}
                        <span className="hidden md:inline text-sm font-bold text-gray-900 break-words whitespace-normal">{receipt.receiptNumber}</span>
                      </td>
                      <td className="hidden md:table-cell p-4 md:p-6 text-sm text-gray-700">
                        {new Date(receipt.createdAt).toLocaleDateString()}
                      </td>
                      <td className="hidden md:table-cell p-4 md:p-6">
                        <span className="px-2.5 py-1 bg-blue-50 border border-blue-100 text-blue-700 rounded-full text-xs font-bold inline-block">
                          {receipt.category}
                        </span>
                      </td>
                      <td className="hidden md:table-cell p-4 md:p-6 text-sm text-gray-900 font-bold break-words whitespace-normal">
                        {receipt.dynamicData?.donorName || receipt.dynamicData?.name || receipt.dynamicData?.subject || 'N/A'}
                      </td>
                      <td className="hidden md:table-cell p-4 md:p-6 text-sm text-gray-700 break-words whitespace-normal">
                        {receipt.branchId?.name || 'Main Trust'}
                      </td>
                      <td className="hidden md:table-cell p-4 md:p-6 text-sm text-gray-700 break-words whitespace-normal">
                        {receipt.generatedBy?.name || receipt.generatedBy?.fullName || receipt.generatedBy?.displayName || 'System'}
                      </td>
                      {/* Mobile Footer & Desktop Actions */}
                      <td className="p-3 md:p-6 block md:table-cell bg-gray-50 md:bg-transparent rounded-b-xl md:rounded-none">
                        <div className="flex md:hidden justify-between items-center mb-3 px-1">
                          <span className="text-[11px] text-gray-500 font-medium bg-white px-2 py-1 rounded border border-gray-200">{new Date(receipt.createdAt).toLocaleDateString()}</span>
                          <span className="text-[11px] text-gray-500 truncate max-w-[120px]">By: {receipt.generatedBy?.name || receipt.generatedBy?.fullName || receipt.generatedBy?.displayName || 'System'}</span>
                        </div>
                        <div className="flex justify-between md:justify-end gap-2 border-t border-gray-200 md:border-none pt-3 md:pt-0">
                          {receipt.pdfUrl ? (
                            <>
                              <a href={receipt.pdfUrl} target="_blank" rel="noopener noreferrer" className="flex-1 md:flex-none p-2 flex items-center justify-center bg-white md:bg-transparent text-gray-600 border md:border-none border-gray-200 hover:bg-gray-100 rounded-lg shadow-sm md:shadow-none" title="View PDF">
                                <Eye className="w-4 h-4 md:w-5 md:h-5" />
                              </a>
                              <a href={receipt.pdfUrl} download className="flex-1 md:flex-none p-2 flex items-center justify-center bg-white md:bg-transparent text-gray-600 border md:border-none border-gray-200 hover:bg-gray-100 rounded-lg shadow-sm md:shadow-none" title="Download">
                                <Download className="w-4 h-4 md:w-5 md:h-5" />
                              </a>
                              <button className="flex-1 md:flex-none p-2 flex items-center justify-center bg-white md:bg-transparent text-gray-600 border md:border-none border-gray-200 hover:bg-gray-100 rounded-lg shadow-sm md:shadow-none" title="Share via WhatsApp" onClick={() => window.open(`https://api.whatsapp.com/send?text=View your document here: ${receipt.pdfUrl}`, '_blank')}>
                                <Share2 className="w-4 h-4 md:w-5 md:h-5" />
                              </button>
                            </>
                          ) : (
                            <span className="text-xs text-gray-400 w-full text-center md:text-right py-2 md:py-0">PDF Pending</span>
                          )}
                        </div>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReceiptHistory;



