import React, { useState, useEffect } from 'react';
import api from '../../utils/api';
import { Search, Download, Share2, Printer, Eye } from 'lucide-react';
import toast from 'react-hot-toast';

const ReceiptHistory = ({ defaultCategory = 'All', hideTitle = false }) => {
  const [receipts, setReceipts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [filters, setFilters] = useState({
    category: defaultCategory,
    branchId: 'All',
    search: ''
  });

  const categories = ['All', 'Notice', 'Donation', 'Branch Donation', 'Annadan', 'Prasad', 'Payment', 'Expense'];

  const fetchReceipts = async () => {
    try {
      setLoading(true);
      const queryParams = new URLSearchParams(filters).toString();
      const res = await api.get(`/receipts?${queryParams}`);
      if (res.data.success) {
        setReceipts(res.data.data);
      }
    } catch (error) {
      toast.error('Failed to load receipts');
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReceipts();
  }, [filters.category, filters.branchId]);

  const handleSearch = (e) => {
    e.preventDefault();
    fetchReceipts();
  };

  return (
    <div className="p-6 bg-gray-50 min-h-screen">
      <div className="max-w-7xl mx-auto">
        {!hideTitle && <h1 className="text-3xl font-bold text-gray-800 mb-8 border-b pb-4">Document & Receipt History</h1>}

        {/* Filters */}
        <div className="bg-white p-4 rounded-xl shadow-sm mb-6 flex flex-wrap gap-4 items-end">
          <div className="flex-1 min-w-[200px]">
            <label className="block text-sm font-medium text-gray-700 mb-1">Search Document No.</label>
            <form onSubmit={handleSearch} className="relative">
              <input
                type="text"
                placeholder="Search REC-..."
                className="w-full pl-10 pr-4 py-2 border rounded-lg focus:ring-2 focus:ring-red-500 outline-none"
                value={filters.search}
                onChange={(e) => setFilters({ ...filters, search: e.target.value })}
              />
              <Search className="absolute left-3 top-2.5 text-gray-400 w-5 h-5" />
            </form>
          </div>
          
          <div className="min-w-[150px]">
            <label className="block text-sm font-medium text-gray-700 mb-1">Category</label>
            <select
              className="w-full p-2 border rounded-lg bg-gray-50"
              value={filters.category}
              onChange={(e) => setFilters({ ...filters, category: e.target.value })}
            >
              {categories.map(cat => <option key={cat} value={cat}>{cat}</option>)}
            </select>
          </div>
          
          <button 
            onClick={fetchReceipts}
            className="px-6 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 transition"
          >
            Apply Filters
          </button>
        </div>

        {/* Table */}
        <div className="bg-white rounded-xl shadow-sm overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm">
              <thead className="bg-gray-100 text-gray-700">
                <tr>
                  <th className="p-4 font-semibold">Document No</th>
                  <th className="p-4 font-semibold">Date</th>
                  <th className="p-4 font-semibold">Category</th>
                  <th className="p-4 font-semibold">Recipient</th>
                  <th className="p-4 font-semibold">Branch</th>
                  <th className="p-4 font-semibold">Generated By</th>
                  <th className="p-4 font-semibold text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y">
                {loading ? (
                  <tr><td colSpan="6" className="text-center p-8 text-gray-500">Loading documents...</td></tr>
                ) : receipts.length === 0 ? (
                  <tr><td colSpan="6" className="text-center p-8 text-gray-500">No documents found matching filters</td></tr>
                ) : (
                  receipts.map(receipt => (
                    <tr key={receipt._id} className="hover:bg-gray-50 transition">
                      <td className="p-4 font-medium text-gray-900">{receipt.receiptNumber}</td>
                      <td className="p-4 text-gray-600">
                        {new Date(receipt.createdAt).toLocaleDateString()}
                      </td>
                      <td className="p-4">
                        <span className="px-3 py-1 bg-blue-100 text-blue-700 rounded-full text-xs font-semibold">
                          {receipt.category}
                        </span>
                      </td>
                      <td className="p-4 font-medium text-gray-800">
                        {receipt.dynamicData?.donorName || receipt.dynamicData?.name || receipt.dynamicData?.subject || 'N/A'}
                      </td>
                      <td className="p-4 text-gray-600">{receipt.branchId?.name || 'Main Trust'}</td>
                      <td className="p-4 text-gray-600">
                        {receipt.generatedBy?.name || receipt.generatedBy?.fullName || receipt.generatedBy?.displayName || 'System'}
                      </td>
                      <td className="p-4 flex justify-end gap-2">
                        {receipt.pdfUrl ? (
                          <>
                            <a href={receipt.pdfUrl} target="_blank" rel="noopener noreferrer" className="p-2 text-gray-500 hover:bg-gray-100 rounded-lg" title="View PDF">
                              <Eye className="w-5 h-5" />
                            </a>
                            <a href={receipt.pdfUrl} download className="p-2 text-gray-500 hover:bg-gray-100 rounded-lg" title="Download">
                              <Download className="w-5 h-5" />
                            </a>
                            <button className="p-2 text-gray-500 hover:bg-gray-100 rounded-lg" title="Share via WhatsApp" onClick={() => window.open(`https://api.whatsapp.com/send?text=View your document here: ${receipt.pdfUrl}`, '_blank')}>
                              <Share2 className="w-5 h-5" />
                            </button>
                          </>
                        ) : (
                          <span className="text-xs text-gray-400">PDF Pending</span>
                        )}
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReceiptHistory;
